
[mqtt]
user="USER"
password="PASSWORD"
serverAddress="tcp://192.168.4.16:1883"


[device_nodered]
watchTimeOut=2
watchTopics="home/agents/nodered/watchdog"


[device_agent_wifi_measure]
watchTimeOut=30
watchTopics="home/esp10/sensors/#"

[device_esp10]
watchTimeOut=60
helloTopic="home/esp10"
watchTopics="home/esp10/sensors/#"
stateTopics="home/esp10/actuators/#"

[device_esp08]
watchTimeOut=60
helloTopic="home/esp08"
watchTopics="home/esp08/sensors/#"
stateTopics="home/esp08/actuators/relay1"

[device_esp04]
watchTimeOut=60
helloTopic="home/esp04"
watchTopics="home/esp04/sensors/#"
stateTopics="home/esp04/actuators/#"

[device_esp03]
watchTimeOut=60
helloTopic="home/esp03"
watchTopics="home/esp03/sensors/#"
stateTopics="home/esp03/actuators/#"

# METEO
[device_esp05]
watchTimeOut=1200
helloTopic="home/esp05"
watchTopics="home/esp03/sensors/#"

